/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsAquaFishFeedRouteImport } from './routes/products/aqua-fish-feed'
import { Route as ProductsCattleDairyFeedRouteImport } from './routes/products/cattle-dairy-feed'
import { Route as ProductsGoatSwineMineralsRouteImport } from './routes/products/goat-swine-minerals'
import { Route as ProductsPoultryFeedRouteImport } from './routes/products/poultry-feed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAquaFishFeedRoute = ProductsAquaFishFeedRouteImport.update({
  id: '/products/aqua-fish-feed',
  path: '/products/aqua-fish-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCattleDairyFeedRoute = ProductsCattleDairyFeedRouteImport.update({
  id: '/products/cattle-dairy-feed',
  path: '/products/cattle-dairy-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGoatSwineMineralsRoute =
  ProductsGoatSwineMineralsRouteImport.update({
    id: '/products/goat-swine-minerals',
    path: '/products/goat-swine-minerals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsPoultryFeedRoute = ProductsPoultryFeedRouteImport.update({
  id: '/products/poultry-feed',
  path: '/products/poultry-feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products/aqua-fish-feed': typeof ProductsAquaFishFeedRoute
  '/products/cattle-dairy-feed': typeof ProductsCattleDairyFeedRoute
  '/products/goat-swine-minerals': typeof ProductsGoatSwineMineralsRoute
  '/products/poultry-feed': typeof ProductsPoultryFeedRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products/aqua-fish-feed': typeof ProductsAquaFishFeedRoute
  '/products/cattle-dairy-feed': typeof ProductsCattleDairyFeedRoute
  '/products/goat-swine-minerals': typeof ProductsGoatSwineMineralsRoute
  '/products/poultry-feed': typeof ProductsPoultryFeedRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products/aqua-fish-feed': typeof ProductsAquaFishFeedRoute
  '/products/cattle-dairy-feed': typeof ProductsCattleDairyFeedRoute
  '/products/goat-swine-minerals': typeof ProductsGoatSwineMineralsRoute
  '/products/poultry-feed': typeof ProductsPoultryFeedRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/products/aqua-fish-feed'
    | '/products/cattle-dairy-feed'
    | '/products/goat-swine-minerals'
    | '/products/poultry-feed'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/products/aqua-fish-feed'
    | '/products/cattle-dairy-feed'
    | '/products/goat-swine-minerals'
    | '/products/poultry-feed'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/products/aqua-fish-feed'
    | '/products/cattle-dairy-feed'
    | '/products/goat-swine-minerals'
    | '/products/poultry-feed'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductsAquaFishFeedRoute: typeof ProductsAquaFishFeedRoute
  ProductsCattleDairyFeedRoute: typeof ProductsCattleDairyFeedRoute
  ProductsGoatSwineMineralsRoute: typeof ProductsGoatSwineMineralsRoute
  ProductsPoultryFeedRoute: typeof ProductsPoultryFeedRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/aqua-fish-feed': {
      id: '/products/aqua-fish-feed'
      path: '/products/aqua-fish-feed'
      fullPath: '/products/aqua-fish-feed'
      preLoaderRoute: typeof ProductsAquaFishFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/cattle-dairy-feed': {
      id: '/products/cattle-dairy-feed'
      path: '/products/cattle-dairy-feed'
      fullPath: '/products/cattle-dairy-feed'
      preLoaderRoute: typeof ProductsCattleDairyFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/goat-swine-minerals': {
      id: '/products/goat-swine-minerals'
      path: '/products/goat-swine-minerals'
      fullPath: '/products/goat-swine-minerals'
      preLoaderRoute: typeof ProductsGoatSwineMineralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/poultry-feed': {
      id: '/products/poultry-feed'
      path: '/products/poultry-feed'
      fullPath: '/products/poultry-feed'
      preLoaderRoute: typeof ProductsPoultryFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductsAquaFishFeedRoute: ProductsAquaFishFeedRoute,
  ProductsCattleDairyFeedRoute: ProductsCattleDairyFeedRoute,
  ProductsGoatSwineMineralsRoute: ProductsGoatSwineMineralsRoute,
  ProductsPoultryFeedRoute: ProductsPoultryFeedRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
